title: Upload from Github Actions to GPR
tagline: Upload to GPR with Github Actions
description: Upload to GPR with Github Actions
template:
  repo: actions-to-gpr-tempalte
  name: actions-to-gpr
  description: >-
    A course to learn how to upload to Github Package Registry using Github
    Actions
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: ''
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
